# Load Blockusters

In [49]:
import pandas as pd
import json

In [50]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [51]:
with open("/content/drive/MyDrive/Data Science Portfolio/Data Analysis/Project 2/blockbusters.json") as f:
  data = json.load(f)

In [52]:
# read json file
data

[{'title': 'Avengers: Endgame',
  'id': 299534,
  'revenue': 2797800564,
  'genres': [{'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'}],
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
  'runtime': 181},
 {'title': 'Avatar',
  'id': 19995,
  'revenue': 2787965087,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 14, 'name': 'Fantasy'},
   {'id': 878, 'name': 'Science Fiction'}],
  'belongs_to_collection': {'id': 87096,
   'name': 'Avatar Collection',
   'poster_path': '/nslJVsO58Etqkk17oXMuVK4gNOF.jpg',
   'backdrop_path': '/8nCr9W7sKus2q9PLbYsnT7iCkuT.jpg'},
  'runtime': 162},
 {'title': 'Star Wars: The Force Awakens',
  'id': 140607,
  'revenue': 2068223624,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 14, 'name': 'Fantasy'}],
  'belongs_to_collection': {'id': 10,
   'name': 'Star Wars Collection',
   'poster_path': '/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg',
   'backdrop_path': '/d8duYyyC9J5T825Hg7grmaabfxQ.jpg'},
  'runtime': 136},
 {'title': 'Avengers: Infinity War',
  'id': 299536,
  'revenue': 2046239637,
  'genres': [{'id': 12, 'name': 'Adventure'},
   {'id': 28, 'name': 'Action'},
   {'id': 878, 'name': 'Science Fiction'}],
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
  'runtime': 149},
 {'title': 'Titanic',
  'id': 597,
  'revenue': 1845034188,
  'genres': [{'id': 18, 'name': 'Drama'},
   {'id': 10749, 'name': 'Romance'},
   {'id': 53, 'name': 'Thriller'}],
  'belongs_to_collection': None,
  'runtime': 194},
 {'title': 'Jurassic World',
  'id': 135397,
  'revenue': 1671713208,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 53, 'name': 'Thriller'}],
  'belongs_to_collection': {'id': 328,
   'name': 'Jurassic Park Collection',
   'poster_path': '/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg',
   'backdrop_path': '/pJjIH9QN0OkHFV9eue6XfRVnPkr.jpg'},
  'runtime': 124},
 {'title': 'The Lion King',
  'id': 420818,
  'revenue': 1656943394,
  'genres': [{'id': 12, 'name': 'Adventure'}, {'id': 10751, 'name': 'Family'}],
  'belongs_to_collection': None,
  'runtime': 118},
 {'title': 'The Avengers',
  'id': 24428,
  'revenue': 1519557910,
  'genres': [{'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'}],
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
  'runtime': 143},
 {'title': 'Furious 7',
  'id': 168259,
  'revenue': 1506249360,
  'genres': [{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}],
  'belongs_to_collection': {'id': 9485,
   'name': 'The Fast and the Furious Collection',
   'poster_path': '/uv63yAGg1zETAs1XQsOQpava87l.jpg',
   'backdrop_path': '/z5A5W3WYJc3UVEWljSGwdjDgQ0j.jpg'},
  'runtime': 137},
 {'title': 'Avengers: Age of Ultron',
  'id': 99861,
  'revenue': 1405403694,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'}],
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
  'runtime': 141},
 {'title': 'Black Panther',
  'id': 284054,
  'revenue': 1346739107,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 14, 'name': 'Fantasy'},
   {'id': 878, 'name': 'Science Fiction'}],
  'belongs_to_collection': {'id': 529892,
   'name': 'Black Panther Collection',
   'poster_path': '/9ZSPIsxI3TZDgfg0Jzk0RZl4INg.jpg',
   'backdrop_path': '/1Jj7Frjjbewb6Q6dl6YXhL3kuvL.jpg'},
  'runtime': 134},
 {'title': 'Harry Potter and the Deathly Hallows: Part 2',
  'id': 12445,
  'revenue': 1341511219,
  'genres': [{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'name': 'Adventure'}],
  'belongs_to_collection': {'id': 1241,
   'name': 'Harry Potter Collection',
   'poster_path': '/eVPs2Y0LyvTLZn6AP5Z6O2rtiGB.jpg',
   'backdrop_path': '/wfnMt6LGqYHcNyOfsuusw5lX3bL.jpg'},
  'runtime': 130},
 {'title': 'Star Wars: The Last Jedi',
  'id': 181808,
  'revenue': 1332539889,
  'genres': [{'id': 14, 'name': 'Fantasy'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'}],
  'belongs_to_collection': {'id': 10,
   'name': 'Star Wars Collection',
   'poster_path': '/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg',
   'backdrop_path': '/d8duYyyC9J5T825Hg7grmaabfxQ.jpg'},
  'runtime': 152},
 {'title': 'Frozen II',
  'id': 330457,
  'revenue': 1330764959,
  'genres': [{'id': 16, 'name': 'Animation'},
   {'id': 10751, 'name': 'Family'},
   {'id': 12, 'name': 'Adventure'}],
  'belongs_to_collection': {'id': 386382,
   'name': 'Frozen Collection',
   'poster_path': '/rpoXnE9UzCbjmINhxIi8bZF557B.jpg',
   'backdrop_path': '/vZiqhw6oFoMlHSneIdVip9rRou2.jpg'},
  'runtime': 104},
 {'title': 'Jurassic World: Fallen Kingdom',
  'id': 351286,
  'revenue': 1303459585,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'}],
  'belongs_to_collection': {'id': 328,
   'name': 'Jurassic Park Collection',
   'poster_path': '/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg',
   'backdrop_path': '/pJjIH9QN0OkHFV9eue6XfRVnPkr.jpg'},
  'runtime': 129},
 {'title': 'Frozen',
  'id': 109445,
  'revenue': 1274219009,
  'genres': [{'id': 16, 'name': 'Animation'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 10751, 'name': 'Family'}],
  'belongs_to_collection': {'id': 386382,
   'name': 'Frozen Collection',
   'poster_path': '/rpoXnE9UzCbjmINhxIi8bZF557B.jpg',
   'backdrop_path': '/vZiqhw6oFoMlHSneIdVip9rRou2.jpg'},
  'runtime': 102},
 {'title': 'Beauty and the Beast',
  'id': 321612,
  'revenue': 1263521126,
  'genres': [{'id': 10751, 'name': 'Family'},
   {'id': 14, 'name': 'Fantasy'},
   {'id': 10749, 'name': 'Romance'}],
  'belongs_to_collection': None,
  'runtime': 129},
 {'title': 'Incredibles 2',
  'id': 260513,
  'revenue': 1241891456,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 16, 'name': 'Animation'},
   {'id': 10751, 'name': 'Family'}],
  'belongs_to_collection': {'id': 468222,
   'name': 'The Incredibles Collection',
   'poster_path': '/l7GqbzkJwowYRIXAtUz2iCPi64a.jpg',
   'backdrop_path': '/9eDW2dVhnzPS2HvaRdK2OlAGaLq.jpg'},
  'runtime': 118}]

In [53]:
# convert json to dataframe
df = pd.read_json("/content/drive/MyDrive/Data Science Portfolio/Data Analysis/Project 2/blockbusters.json")
df.head()

,title,id,revenue,genres,belongs_to_collection,runtime
0,Avengers: Endgame,299534,2797800564,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...","{'id': 86311, 'name': 'The Avengers Collection...",181
1,Avatar,19995,2787965087,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 87096, 'name': 'Avatar Collection', 'po...",162
2,Star Wars: The Force Awakens,140607,2068223624,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 10, 'name': 'Star Wars Collection', 'po...",136
3,Avengers: Infinity War,299536,2046239637,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","{'id': 86311, 'name': 'The Avengers Collection...",149
4,Titanic,597,1845034188,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",None,194

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   title                  18 non-null     object
 1   id                     18 non-null     int64
 2   revenue                18 non-null     int64
 3   genres                 18 non-null     object
 4   belongs_to_collection  15 non-null     object
 5   runtime                18 non-null     int64
dtypes: int64(3), object(3)
memory usage: 992.0+ bytes

In [55]:
df["belongs_to_collection"][0]

{'id': 86311,
 'name': 'The Avengers Collection',
 'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
 'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'}

In [56]:
# to flatten the 'belong_to_collection' column
pd.json_normalize(data, sep = "_").head()

,title,id,revenue,genres,runtime,belongs_to_collection_id,belongs_to_collection_name,belongs_to_collection_poster_path,belongs_to_collection_backdrop_path,belongs_to_collection
0,Avengers: Endgame,299534,2797800564,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",181,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
1,Avatar,19995,2787965087,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",162,87096.0,Avatar Collection,/nslJVsO58Etqkk17oXMuVK4gNOF.jpg,/8nCr9W7sKus2q9PLbYsnT7iCkuT.jpg,NaN
2,Star Wars: The Force Awakens,140607,2068223624,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",136,10.0,Star Wars Collection,/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg,/d8duYyyC9J5T825Hg7grmaabfxQ.jpg,NaN
3,Avengers: Infinity War,299536,2046239637,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",149,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
4,Titanic,597,1845034188,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",194,NaN,NaN,NaN,NaN,NaN

In [71]:
pd.json_normalize(data, sep = "_").genres[0]

AttributeError: 'DataFrame' object has no attribute 'genres'

In [58]:
pd.json_normalize(data, record_path = "genres", meta = ["title", "id"], record_prefix = "genre_")

,genre_id,genre_name,title,id
0,12,Adventure,Avengers: Endgame,299534
1,878,Science Fiction,Avengers: Endgame,299534
2,28,Action,Avengers: Endgame,299534
3,28,Action,Avatar,19995
4,12,Adventure,Avatar,19995
5,14,Fantasy,Avatar,19995
6,878,Science Fiction,Avatar,19995
7,28,Action,Star Wars: The Force Awakens,140607
8,12,Adventure,Star Wars: The Force Awakens,140607
9,878,Science Fiction,Star Wars: The Force Awakens,140607
10,14,Fantasy,Star Wars: The Force Awakens,140607
11,12,Adventure,Avengers: Infinity War,299536
12,28,Action,Avengers: Infinity War,299536
13,878,Science Fiction,Avengers: Infinity War,299536
14,18,Drama,Titanic,597
15,10749,Romance,Titanic,597
16,53,Thriller,Titanic,597
17,28,Action,Jurassic World,135397
18,12,Adventure,Jurassic World,135397
19,878,Science Fiction,Jurassic World,135397
20,53,Thriller,Jurassic World,135397
21,12,Adventure,The Lion King,420818
22,10751,Family,The Lion King,420818
23,878,Science Fiction,The Avengers,24428
24,28,Action,The Avengers,24428
25,12,Adventure,The Avengers,24428
26,28,Action,Furious 7,168259
27,53,Thriller,Furious 7,168259
28,28,Action,Avengers: Age of Ultron,99861
29,12,Adventure,Avengers: Age of Ultron,99861
30,878,Science Fiction,Avengers: Age of Ultron,99861
31,28,Action,Black Panther,284054
32,12,Adventure,Black Panther,284054
33,14,Fantasy,Black Panther,284054
34,878,Science Fiction,Black Panther,284054
35,14,Fantasy,Harry Potter and the Deathly Hallows: Part 2,12445
36,12,Adventure,Harry Potter and the Deathly Hallows: Part 2,12445
37,14,Fantasy,Star Wars: The Last Jedi,181808
38,12,Adventure,Star Wars: The Last Jedi,181808
39,878,Science Fiction,Star Wars: The Last Jedi,181808
40,28,Action,Star Wars: The Last Jedi,181808
41,16,Animation,Frozen II,330457
42,10751,Family,Frozen II,330457
43,12,Adventure,Frozen II,330457
44,28,Action,Jurassic World: Fallen Kingdom,351286
45,12,Adventure,Jurassic World: Fallen Kingdom,351286
46,878,Science Fiction,Jurassic World: Fallen Kingdom,351286
47,16,Animation,Frozen,109445
48,12,Adventure,Frozen,109445
49,10751,Family,Frozen,109445
50,10751,Family,Beauty and the Beast,321612
51,14,Fantasy,Beauty and the Beast,321612
52,10749,Romance,Beauty and the Beast,321612
53,28,Action,Incredibles 2,260513
54,12,Adventure,Incredibles 2,260513
55,16,Animation,Incredibles 2,260513
56,10751,Family,Incredibles 2,260513

# Loading Blockbusters 2

In [67]:
with open ("/content/drive/MyDrive/Data Science Portfolio/Data Analysis/Project 2/blockbusters2.json") as g:
  data = json.load(g)

In [68]:
data

{'title': {'0': 'Avengers: Endgame',
  '1': 'Avatar',
  '2': 'Star Wars: The Force Awakens',
  '3': 'Avengers: Infinity War',
  '4': 'Titanic',
  '5': 'Jurassic World',
  '6': 'The Lion King',
  '7': 'The Avengers',
  '8': 'Furious 7',
  '9': 'Avengers: Age of Ultron',
  '10': 'Black Panther',
  '11': 'Harry Potter and the Deathly Hallows: Part 2',
  '12': 'Star Wars: The Last Jedi',
  '13': 'Frozen II',
  '14': 'Jurassic World: Fallen Kingdom',
  '15': 'Frozen',
  '16': 'Beauty and the Beast',
  '17': 'Incredibles 2'},
 'id': {'0': 299534,
  '1': 19995,
  '2': 140607,
  '3': 299536,
  '4': 597,
  '5': 135397,
  '6': 420818,
  '7': 24428,
  '8': 168259,
  '9': 99861,
  '10': 284054,
  '11': 12445,
  '12': 181808,
  '13': 330457,
  '14': 351286,
  '15': 109445,
  '16': 321612,
  '17': 260513},
 'revenue': {'0': 2797800564,
  '1': 2787965087,
  '2': 2068223624,
  '3': 2046239637,
  '4': 1845034188,
  '5': 1671713208,
  '6': 1656943394,
  '7': 1519557910,
  '8': 1506249360,
  '9': 1405403694,
  '10': 1346739107,
  '11': 1341511219,
  '12': 1332539889,
  '13': 1330764959,
  '14': 1303459585,
  '15': 1274219009,
  '16': 1263521126,
  '17': 1241891456},
 'genres': {'0': [{'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'}],
  '1': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 14, 'name': 'Fantasy'},
   {'id': 878, 'name': 'Science Fiction'}],
  '2': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 14, 'name': 'Fantasy'}],
  '3': [{'id': 12, 'name': 'Adventure'},
   {'id': 28, 'name': 'Action'},
   {'id': 878, 'name': 'Science Fiction'}],
  '4': [{'id': 18, 'name': 'Drama'},
   {'id': 10749, 'name': 'Romance'},
   {'id': 53, 'name': 'Thriller'}],
  '5': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 53, 'name': 'Thriller'}],
  '6': [{'id': 12, 'name': 'Adventure'}, {'id': 10751, 'name': 'Family'}],
  '7': [{'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'}],
  '8': [{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}],
  '9': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'}],
  '10': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 14, 'name': 'Fantasy'},
   {'id': 878, 'name': 'Science Fiction'}],
  '11': [{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'name': 'Adventure'}],
  '12': [{'id': 14, 'name': 'Fantasy'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'}],
  '13': [{'id': 16, 'name': 'Animation'},
   {'id': 10751, 'name': 'Family'},
   {'id': 12, 'name': 'Adventure'}],
  '14': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'}],
  '15': [{'id': 16, 'name': 'Animation'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 10751, 'name': 'Family'}],
  '16': [{'id': 10751, 'name': 'Family'},
   {'id': 14, 'name': 'Fantasy'},
   {'id': 10749, 'name': 'Romance'}],
  '17': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 16, 'name': 'Animation'},
   {'id': 10751, 'name': 'Family'}]},
 'belongs_to_collection': {'0': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
  '1': {'id': 87096,
   'name': 'Avatar Collection',
   'poster_path': '/nslJVsO58Etqkk17oXMuVK4gNOF.jpg',
   'backdrop_path': '/8nCr9W7sKus2q9PLbYsnT7iCkuT.jpg'},
  '2': {'id': 10,
   'name': 'Star Wars Collection',
   'poster_path': '/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg',
   'backdrop_path': '/d8duYyyC9J5T825Hg7grmaabfxQ.jpg'},
  '3': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
  '4': None,
  '5': {'id': 328,
   'name': 'Jurassic Park Collection',
   'poster_path': '/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg',
   'backdrop_path': '/pJjIH9QN0OkHFV9eue6XfRVnPkr.jpg'},
  '6': None,
  '7': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
  '8': {'id': 9485,
   'name': 'The Fast and the Furious Collection',
   'poster_path': '/uv63yAGg1zETAs1XQsOQpava87l.jpg',
   'backdrop_path': '/z5A5W3WYJc3UVEWljSGwdjDgQ0j.jpg'},
  '9': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
  '10': {'id': 529892,
   'name': 'Black Panther Collection',
   'poster_path': '/9ZSPIsxI3TZDgfg0Jzk0RZl4INg.jpg',
   'backdrop_path': '/1Jj7Frjjbewb6Q6dl6YXhL3kuvL.jpg'},
  '11': {'id': 1241,
   'name': 'Harry Potter Collection',
   'poster_path': '/eVPs2Y0LyvTLZn6AP5Z6O2rtiGB.jpg',
   'backdrop_path': '/wfnMt6LGqYHcNyOfsuusw5lX3bL.jpg'},
  '12': {'id': 10,
   'name': 'Star Wars Collection',
   'poster_path': '/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg',
   'backdrop_path': '/d8duYyyC9J5T825Hg7grmaabfxQ.jpg'},
  '13': {'id': 386382,
   'name': 'Frozen Collection',
   'poster_path': '/rpoXnE9UzCbjmINhxIi8bZF557B.jpg',
   'backdrop_path': '/vZiqhw6oFoMlHSneIdVip9rRou2.jpg'},
  '14': {'id': 328,
   'name': 'Jurassic Park Collection',
   'poster_path': '/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg',
   'backdrop_path': '/pJjIH9QN0OkHFV9eue6XfRVnPkr.jpg'},
  '15': {'id': 386382,
   'name': 'Frozen Collection',
   'poster_path': '/rpoXnE9UzCbjmINhxIi8bZF557B.jpg',
   'backdrop_path': '/vZiqhw6oFoMlHSneIdVip9rRou2.jpg'},
  '16': None,
  '17': {'id': 468222,
   'name': 'The Incredibles Collection',
   'poster_path': '/l7GqbzkJwowYRIXAtUz2iCPi64a.jpg',
   'backdrop_path': '/9eDW2dVhnzPS2HvaRdK2OlAGaLq.jpg'}},
 'runtime': {'0': 181,
  '1': 162,
  '2': 136,
  '3': 149,
  '4': 194,
  '5': 124,
  '6': 118,
  '7': 143,
  '8': 137,
  '9': 141,
  '10': 134,
  '11': 130,
  '12': 152,
  '13': 104,
  '14': 129,
  '15': 102,
  '16': 129,
  '17': 118}}

In [69]:
df = pd.DataFrame(data)
df.head()

,title,id,revenue,genres,belongs_to_collection,runtime
0,Avengers: Endgame,299534,2797800564,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...","{'id': 86311, 'name': 'The Avengers Collection...",181
1,Avatar,19995,2787965087,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 87096, 'name': 'Avatar Collection', 'po...",162
2,Star Wars: The Force Awakens,140607,2068223624,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 10, 'name': 'Star Wars Collection', 'po...",136
3,Avengers: Infinity War,299536,2046239637,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","{'id': 86311, 'name': 'The Avengers Collection...",149
4,Titanic,597,1845034188,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",None,194

In [70]:
df = pd.read_json("/content/drive/MyDrive/Data Science Portfolio/Data Analysis/Project 2/blockbusters2.json")
df.head()

,title,id,revenue,genres,belongs_to_collection,runtime
0,Avengers: Endgame,299534,2797800564,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...","{'id': 86311, 'name': 'The Avengers Collection...",181
1,Avatar,19995,2787965087,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 87096, 'name': 'Avatar Collection', 'po...",162
2,Star Wars: The Force Awakens,140607,2068223624,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 10, 'name': 'Star Wars Collection', 'po...",136
3,Avengers: Infinity War,299536,2046239637,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","{'id': 86311, 'name': 'The Avengers Collection...",149
4,Titanic,597,1845034188,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",None,194

In [72]:
# normalize doesn't work with column orientation
pd.json_normalize(data, sep = "_")

,title_0,title_1,title_2,title_3,title_4,title_5,title_6,title_7,title_8,title_9,...,runtime_8,runtime_9,runtime_10,runtime_11,runtime_12,runtime_13,runtime_14,runtime_15,runtime_16,runtime_17
0,Avengers: Endgame,Avatar,Star Wars: The Force Awakens,Avengers: Infinity War,Titanic,Jurassic World,The Lion King,The Avengers,Furious 7,Avengers: Age of Ultron,...,137,141,134,130,152,104,129,102,129,118

# Loading Blockbusters 3

In [62]:
with open ("/content/drive/MyDrive/Data Science Portfolio/Data Analysis/Project 2/blockbusters3.json") as h:
  data = json.load(h)

In [63]:
data

{'columns': ['title',
  'id',
  'revenue',
  'genres',
  'belongs_to_collection',
  'runtime'],
 'index': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
 'data': [['Avengers: Endgame',
   299534,
   2797800564,
   [{'id': 12, 'name': 'Adventure'},
    {'id': 878, 'name': 'Science Fiction'},
    {'id': 28, 'name': 'Action'}],
   {'id': 86311,
    'name': 'The Avengers Collection',
    'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
    'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
   181],
  ['Avatar',
   19995,
   2787965087,
   [{'id': 28, 'name': 'Action'},
    {'id': 12, 'name': 'Adventure'},
    {'id': 14, 'name': 'Fantasy'},
    {'id': 878, 'name': 'Science Fiction'}],
   {'id': 87096,
    'name': 'Avatar Collection',
    'poster_path': '/nslJVsO58Etqkk17oXMuVK4gNOF.jpg',
    'backdrop_path': '/8nCr9W7sKus2q9PLbYsnT7iCkuT.jpg'},
   162],
  ['Star Wars: The Force Awakens',
   140607,
   2068223624,
   [{'id': 28, 'name': 'Action'},
    {'id': 12, 'name': 'Adventure'},
    {'id': 878, 'name': 'Science Fiction'},
    {'id': 14, 'name': 'Fantasy'}],
   {'id': 10,
    'name': 'Star Wars Collection',
    'poster_path': '/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg',
    'backdrop_path': '/d8duYyyC9J5T825Hg7grmaabfxQ.jpg'},
   136],
  ['Avengers: Infinity War',
   299536,
   2046239637,
   [{'id': 12, 'name': 'Adventure'},
    {'id': 28, 'name': 'Action'},
    {'id': 878, 'name': 'Science Fiction'}],
   {'id': 86311,
    'name': 'The Avengers Collection',
    'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
    'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
   149],
  ['Titanic',
   597,
   1845034188,
   [{'id': 18, 'name': 'Drama'},
    {'id': 10749, 'name': 'Romance'},
    {'id': 53, 'name': 'Thriller'}],
   None,
   194],
  ['Jurassic World',
   135397,
   1671713208,
   [{'id': 28, 'name': 'Action'},
    {'id': 12, 'name': 'Adventure'},
    {'id': 878, 'name': 'Science Fiction'},
    {'id': 53, 'name': 'Thriller'}],
   {'id': 328,
    'name': 'Jurassic Park Collection',
    'poster_path': '/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg',
    'backdrop_path': '/pJjIH9QN0OkHFV9eue6XfRVnPkr.jpg'},
   124],
  ['The Lion King',
   420818,
   1656943394,
   [{'id': 12, 'name': 'Adventure'}, {'id': 10751, 'name': 'Family'}],
   None,
   118],
  ['The Avengers',
   24428,
   1519557910,
   [{'id': 878, 'name': 'Science Fiction'},
    {'id': 28, 'name': 'Action'},
    {'id': 12, 'name': 'Adventure'}],
   {'id': 86311,
    'name': 'The Avengers Collection',
    'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
    'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
   143],
  ['Furious 7',
   168259,
   1506249360,
   [{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}],
   {'id': 9485,
    'name': 'The Fast and the Furious Collection',
    'poster_path': '/uv63yAGg1zETAs1XQsOQpava87l.jpg',
    'backdrop_path': '/z5A5W3WYJc3UVEWljSGwdjDgQ0j.jpg'},
   137],
  ['Avengers: Age of Ultron',
   99861,
   1405403694,
   [{'id': 28, 'name': 'Action'},
    {'id': 12, 'name': 'Adventure'},
    {'id': 878, 'name': 'Science Fiction'}],
   {'id': 86311,
    'name': 'The Avengers Collection',
    'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
    'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
   141],
  ['Black Panther',
   284054,
   1346739107,
   [{'id': 28, 'name': 'Action'},
    {'id': 12, 'name': 'Adventure'},
    {'id': 14, 'name': 'Fantasy'},
    {'id': 878, 'name': 'Science Fiction'}],
   {'id': 529892,
    'name': 'Black Panther Collection',
    'poster_path': '/9ZSPIsxI3TZDgfg0Jzk0RZl4INg.jpg',
    'backdrop_path': '/1Jj7Frjjbewb6Q6dl6YXhL3kuvL.jpg'},
   134],
  ['Harry Potter and the Deathly Hallows: Part 2',
   12445,
   1341511219,
   [{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'name': 'Adventure'}],
   {'id': 1241,
    'name': 'Harry Potter Collection',
    'poster_path': '/eVPs2Y0LyvTLZn6AP5Z6O2rtiGB.jpg',
    'backdrop_path': '/wfnMt6LGqYHcNyOfsuusw5lX3bL.jpg'},
   130],
  ['Star Wars: The Last Jedi',
   181808,
   1332539889,
   [{'id': 14, 'name': 'Fantasy'},
    {'id': 12, 'name': 'Adventure'},
    {'id': 878, 'name': 'Science Fiction'},
    {'id': 28, 'name': 'Action'}],
   {'id': 10,
    'name': 'Star Wars Collection',
    'poster_path': '/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg',
    'backdrop_path': '/d8duYyyC9J5T825Hg7grmaabfxQ.jpg'},
   152],
  ['Frozen II',
   330457,
   1330764959,
   [{'id': 16, 'name': 'Animation'},
    {'id': 10751, 'name': 'Family'},
    {'id': 12, 'name': 'Adventure'}],
   {'id': 386382,
    'name': 'Frozen Collection',
    'poster_path': '/rpoXnE9UzCbjmINhxIi8bZF557B.jpg',
    'backdrop_path': '/vZiqhw6oFoMlHSneIdVip9rRou2.jpg'},
   104],
  ['Jurassic World: Fallen Kingdom',
   351286,
   1303459585,
   [{'id': 28, 'name': 'Action'},
    {'id': 12, 'name': 'Adventure'},
    {'id': 878, 'name': 'Science Fiction'}],
   {'id': 328,
    'name': 'Jurassic Park Collection',
    'poster_path': '/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg',
    'backdrop_path': '/pJjIH9QN0OkHFV9eue6XfRVnPkr.jpg'},
   129],
  ['Frozen',
   109445,
   1274219009,
   [{'id': 16, 'name': 'Animation'},
    {'id': 12, 'name': 'Adventure'},
    {'id': 10751, 'name': 'Family'}],
   {'id': 386382,
    'name': 'Frozen Collection',
    'poster_path': '/rpoXnE9UzCbjmINhxIi8bZF557B.jpg',
    'backdrop_path': '/vZiqhw6oFoMlHSneIdVip9rRou2.jpg'},
   102],
  ['Beauty and the Beast',
   321612,
   1263521126,
   [{'id': 10751, 'name': 'Family'},
    {'id': 14, 'name': 'Fantasy'},
    {'id': 10749, 'name': 'Romance'}],
   None,
   129],
  ['Incredibles 2',
   260513,
   1241891456,
   [{'id': 28, 'name': 'Action'},
    {'id': 12, 'name': 'Adventure'},
    {'id': 16, 'name': 'Animation'},
    {'id': 10751, 'name': 'Family'}],
   {'id': 468222,
    'name': 'The Incredibles Collection',
    'poster_path': '/l7GqbzkJwowYRIXAtUz2iCPi64a.jpg',
    'backdrop_path': '/9eDW2dVhnzPS2HvaRdK2OlAGaLq.jpg'},
   118]]}

In [64]:
df = pd.DataFrame(data)
df.head()

ValueError: All arrays must be of the same length

In [65]:
df = pd.read_json("/content/drive/MyDrive/Data Science Portfolio/Data Analysis/Project 2/blockbusters3.json", orient = "split")
df

,title,id,revenue,genres,belongs_to_collection,runtime
0,Avengers: Endgame,299534,2797800564,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...","{'id': 86311, 'name': 'The Avengers Collection...",181
1,Avatar,19995,2787965087,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 87096, 'name': 'Avatar Collection', 'po...",162
2,Star Wars: The Force Awakens,140607,2068223624,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 10, 'name': 'Star Wars Collection', 'po...",136
3,Avengers: Infinity War,299536,2046239637,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","{'id': 86311, 'name': 'The Avengers Collection...",149
4,Titanic,597,1845034188,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",None,194
5,Jurassic World,135397,1671713208,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 328, 'name': 'Jurassic Park Collection'...",124
6,The Lion King,420818,1656943394,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",None,118
7,The Avengers,24428,1519557910,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...","{'id': 86311, 'name': 'The Avengers Collection...",143
8,Furious 7,168259,1506249360,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...","{'id': 9485, 'name': 'The Fast and the Furious...",137
9,Avengers: Age of Ultron,99861,1405403694,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 86311, 'name': 'The Avengers Collection...",141
10,Black Panther,284054,1346739107,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 529892, 'name': 'Black Panther Collecti...",134
11,Harry Potter and the Deathly Hallows: Part 2,12445,1341511219,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...","{'id': 1241, 'name': 'Harry Potter Collection'...",130
12,Star Wars: The Last Jedi,181808,1332539889,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...","{'id': 10, 'name': 'Star Wars Collection', 'po...",152
13,Frozen II,330457,1330764959,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...","{'id': 386382, 'name': 'Frozen Collection', 'p...",104
14,Jurassic World: Fallen Kingdom,351286,1303459585,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 328, 'name': 'Jurassic Park Collection'...",129
15,Frozen,109445,1274219009,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...","{'id': 386382, 'name': 'Frozen Collection', 'p...",102
16,Beauty and the Beast,321612,1263521126,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",None,129
17,Incredibles 2,260513,1241891456,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 468222, 'name': 'The Incredibles Collec...",118

In [66]:
pd.json_normalize(data, sep = "_")
# not working so only records orientation is prefered in json

,columns,index,data
0,"[title, id, revenue, genres, belongs_to_collec...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[[Avengers: Endgame, 299534, 2797800564, [{'id..."